version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ytauto-postgres
    environment:
      POSTGRES_USER: ytauto
      POSTGRES_PASSWORD: ytauto123
      POSTGRES_DB: ytauto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ytauto"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ytauto-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ytauto-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://ytauto:ytauto123@postgres:5432/ytauto?schema=public
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: